// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	AutomatedActionsCreateOperation  OperationName = "AutomatedActionsCreate"
	AutomatedActionsDeleteOperation  OperationName = "AutomatedActionsDelete"
	AutomatedActionsListOperation    OperationName = "AutomatedActionsList"
	AutomatedActionsReadOperation    OperationName = "AutomatedActionsRead"
	AutomatedActionsUpdateOperation  OperationName = "AutomatedActionsUpdate"
	EvaluationRulesListOperation     OperationName = "EvaluationRulesList"
	EvaluationRulesReadOperation     OperationName = "EvaluationRulesRead"
	EvaluationRulesUpdateOperation   OperationName = "EvaluationRulesUpdate"
	ProjectActivationCreateOperation OperationName = "ProjectActivationCreate"
	ProjectActivationReadOperation   OperationName = "ProjectActivationRead"
	ProjectActivationUpdateOperation OperationName = "ProjectActivationUpdate"
)
