// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *ActionDefinition) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ActionDefinitionSimpleNotification) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.ActionType.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "actionType",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ActionDefinitionSimpleNotificationActionType) Validate() error {
	switch s {
	case "simpleNotification":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s ActionDefinitionSum) Validate() error {
	switch s.Type {
	case ActionDefinitionSimpleNotificationActionDefinitionSum:
		if err := s.ActionDefinitionSimpleNotification.Validate(); err != nil {
			return err
		}
		return nil
	case ActionDefinitionWorkflowsActionDefinitionSum:
		if err := s.ActionDefinitionWorkflows.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *ActionDefinitionWorkflows) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.ActionType.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "actionType",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ActionDefinitionWorkflowsActionType) Validate() error {
	switch s {
	case "workflows":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *AddonDatalakeNoPublicAccess) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s AddonDatalakeNoPublicAccessEvaluationRuleId) Validate() error {
	switch s {
	case "addon-datalake-no-public-access":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *AddonDwhNoPublicAccess) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s AddonDwhNoPublicAccessEvaluationRuleId) Validate() error {
	switch s {
	case "addon-dwh-no-public-access":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *AddonThreatDetectionEnabled) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s AddonThreatDetectionEnabledEvaluationRuleId) Validate() error {
	switch s {
	case "addon-threat-detection-enabled":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *AddonThreatDetections) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s AddonThreatDetectionsEvaluationRuleId) Validate() error {
	switch s {
	case "addon-threat-detections":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *AddonVulnerabilityDetections) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s AddonVulnerabilityDetectionsEvaluationRuleId) Validate() error {
	switch s {
	case "addon-vulnerability-detections":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *AutomatedActionInput) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Action.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "action",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *AutomatedActionOutput) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Action.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "action",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *AutomatedActionsCreateApplicationJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsCreateApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsCreateApplicationJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsCreateApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsCreateApplicationProblemJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsCreateApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsCreateApplicationProblemJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsCreateApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsDeleteApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsDeleteApplicationJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsDeleteApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsDeleteApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsDeleteApplicationProblemJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsDeleteApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsListApplicationJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsListApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsListApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsListApplicationProblemJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsListApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsListApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsListOK) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Items == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Items {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "items",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *AutomatedActionsReadApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsReadApplicationJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsReadApplicationJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsReadApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsReadApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsReadApplicationProblemJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsReadApplicationProblemJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsReadApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsUpdateApplicationJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsUpdateApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsUpdateApplicationJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsUpdateApplicationJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsUpdateApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsUpdateApplicationProblemJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsUpdateApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsUpdateApplicationProblemJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsUpdateApplicationProblemJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AutomatedActionsUpdateApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *BadRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Status.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Detail.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "detail",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s BadRequestDetail) Validate() error {
	switch s {
	case "invalid":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s BadRequestStatus) Validate() error {
	switch s {
	case 400:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *Conflict) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Status.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Detail.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "detail",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ConflictDetail) Validate() error {
	switch s {
	case "conflict":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s ConflictStatus) Validate() error {
	switch s {
	case 409:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *DbaEncryptionEnabled) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s DbaEncryptionEnabledEvaluationRuleId) Validate() error {
	switch s {
	case "dba-encryption-enabled":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *DbaNoPublicIP) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s DbaNoPublicIPEvaluationRuleId) Validate() error {
	switch s {
	case "dba-no-public-ip":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *DiskEncryptionEnabled) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s DiskEncryptionEnabledEvaluationRuleId) Validate() error {
	switch s {
	case "disk-encryption-enabled":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ELBLoggingEnabled) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ELBLoggingEnabledEvaluationRuleId) Validate() error {
	switch s {
	case "elb-logging-enabled":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *EvaluationRule) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Rule.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "rule",
			Error: err,
		})
	}
	if err := func() error {
		if s.IamRolesRequired == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "iamRolesRequired",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s EvaluationRuleID) Validate() error {
	switch s {
	case "server-no-public-ip":
		return nil
	case "disk-encryption-enabled":
		return nil
	case "dba-encryption-enabled":
		return nil
	case "dba-no-public-ip":
		return nil
	case "objectstorage-bucket-acl-changed":
		return nil
	case "addon-datalake-no-public-access":
		return nil
	case "addon-dwh-no-public-access":
		return nil
	case "addon-threat-detection-enabled":
		return nil
	case "elb-logging-enabled":
		return nil
	case "iam-member-operation-detected":
		return nil
	case "nosql-encryption-enabled":
		return nil
	case "addon-threat-detections":
		return nil
	case "addon-vulnerability-detections":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *EvaluationRuleInput) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Rule.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "rule",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *EvaluationRuleUnion) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s EvaluationRuleUnionSum) Validate() error {
	switch s.Type {
	case ServerNoPublicIPEvaluationRuleUnionSum:
		if err := s.ServerNoPublicIP.Validate(); err != nil {
			return err
		}
		return nil
	case DiskEncryptionEnabledEvaluationRuleUnionSum:
		if err := s.DiskEncryptionEnabled.Validate(); err != nil {
			return err
		}
		return nil
	case DbaEncryptionEnabledEvaluationRuleUnionSum:
		if err := s.DbaEncryptionEnabled.Validate(); err != nil {
			return err
		}
		return nil
	case DbaNoPublicIPEvaluationRuleUnionSum:
		if err := s.DbaNoPublicIP.Validate(); err != nil {
			return err
		}
		return nil
	case ObjectStorageBucketACLChangedEvaluationRuleUnionSum:
		if err := s.ObjectStorageBucketACLChanged.Validate(); err != nil {
			return err
		}
		return nil
	case AddonDatalakeNoPublicAccessEvaluationRuleUnionSum:
		if err := s.AddonDatalakeNoPublicAccess.Validate(); err != nil {
			return err
		}
		return nil
	case AddonDwhNoPublicAccessEvaluationRuleUnionSum:
		if err := s.AddonDwhNoPublicAccess.Validate(); err != nil {
			return err
		}
		return nil
	case AddonThreatDetectionEnabledEvaluationRuleUnionSum:
		if err := s.AddonThreatDetectionEnabled.Validate(); err != nil {
			return err
		}
		return nil
	case ELBLoggingEnabledEvaluationRuleUnionSum:
		if err := s.ELBLoggingEnabled.Validate(); err != nil {
			return err
		}
		return nil
	case IAMMemberOperationDetectedEvaluationRuleUnionSum:
		if err := s.IAMMemberOperationDetected.Validate(); err != nil {
			return err
		}
		return nil
	case NoSQLEncryptionEnabledEvaluationRuleUnionSum:
		if err := s.NoSQLEncryptionEnabled.Validate(); err != nil {
			return err
		}
		return nil
	case AddonThreatDetectionsEvaluationRuleUnionSum:
		if err := s.AddonThreatDetections.Validate(); err != nil {
			return err
		}
		return nil
	case AddonVulnerabilityDetectionsEvaluationRuleUnionSum:
		if err := s.AddonVulnerabilityDetections.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *EvaluationRulesListApplicationJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesListApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesListApplicationJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesListApplicationJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesListApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesListApplicationProblemJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesListApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesListApplicationProblemJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesListApplicationProblemJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesListApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesListOK) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Items == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Items {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "items",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *EvaluationRulesReadApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesReadApplicationJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesReadApplicationJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesReadApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesReadApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesReadApplicationProblemJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesReadApplicationProblemJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesReadApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesUpdateApplicationJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesUpdateApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesUpdateApplicationJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesUpdateApplicationJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesUpdateApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesUpdateApplicationProblemJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesUpdateApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesUpdateApplicationProblemJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesUpdateApplicationProblemJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *EvaluationRulesUpdateApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *Forbidden) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Status.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Detail.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "detail",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ForbiddenDetail) Validate() error {
	switch s {
	case "forbidden":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s ForbiddenStatus) Validate() error {
	switch s {
	case 403:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *IAMMemberOperationDetected) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s IAMMemberOperationDetectedEvaluationRuleId) Validate() error {
	switch s {
	case "iam-member-operation-detected":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *NoSQLEncryptionEnabled) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s NoSQLEncryptionEnabledEvaluationRuleId) Validate() error {
	switch s {
	case "nosql-encryption-enabled":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *NotFound) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Status.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Detail.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "detail",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s NotFoundDetail) Validate() error {
	switch s {
	case "not_found":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s NotFoundStatus) Validate() error {
	switch s {
	case 404:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ObjectStorageBucketACLChanged) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ObjectStorageBucketACLChangedEvaluationRuleId) Validate() error {
	switch s {
	case "objectstorage-bucket-acl-changed":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ProjectActivationCreateApplicationJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationCreateApplicationJSONConflict) Validate() error {
	alias := (*Conflict)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationCreateApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationCreateApplicationJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationCreateApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationCreateApplicationProblemJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationCreateApplicationProblemJSONConflict) Validate() error {
	alias := (*Conflict)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationCreateApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationCreateApplicationProblemJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationCreateApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationReadApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationReadApplicationJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationReadApplicationJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationReadApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationReadApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationReadApplicationProblemJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationReadApplicationProblemJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationReadApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationUpdateApplicationJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationUpdateApplicationJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationUpdateApplicationJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationUpdateApplicationJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationUpdateApplicationJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationUpdateApplicationProblemJSONBadRequest) Validate() error {
	alias := (*BadRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationUpdateApplicationProblemJSONForbidden) Validate() error {
	alias := (*Forbidden)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationUpdateApplicationProblemJSONNotFound) Validate() error {
	alias := (*NotFound)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationUpdateApplicationProblemJSONTooManyRequests) Validate() error {
	alias := (*TooManyRequestsHeaders)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProjectActivationUpdateApplicationProblemJSONUnauthorized) Validate() error {
	alias := (*Unauthorized)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ServerNoPublicIP) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.EvaluationRuleId.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "evaluationRuleId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ServerNoPublicIPEvaluationRuleId) Validate() error {
	switch s {
	case "server-no-public-ip":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *TooManyRequests) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Status.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Detail.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "detail",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s TooManyRequestsDetail) Validate() error {
	switch s {
	case "too_many_requests":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *TooManyRequestsHeaders) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "Response",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s TooManyRequestsStatus) Validate() error {
	switch s {
	case 429:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *Unauthorized) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Status.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Detail.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "detail",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s UnauthorizedDetail) Validate() error {
	switch s {
	case "authentication_failed":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s UnauthorizedStatus) Validate() error {
	switch s {
	case 401:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
