// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"time"
)

// SetFake set fake values.
func (s *ActionDefinition) SetFake() {
	{
		{
			s.OneOf.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ActionDefinitionSimpleNotification) SetFake() {
	{
		{
			s.ActionType.SetFake()
		}
	}
	{
		{
			s.ActionParameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ActionDefinitionSimpleNotificationActionType) SetFake() {
	*s = ActionDefinitionSimpleNotificationActionTypeSimpleNotification
}

// SetFake set fake values.
func (s *ActionDefinitionSum) SetFake() {
	var variant ActionDefinitionSimpleNotification

	{
		variant.SetFake()
	}
	s.SetActionDefinitionSimpleNotification(variant)
}

// SetFake set fake values.
func (s *ActionDefinitionWorkflows) SetFake() {
	{
		{
			s.ActionType.SetFake()
		}
	}
	{
		{
			s.ActionParameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ActionDefinitionWorkflowsActionType) SetFake() {
	*s = ActionDefinitionWorkflowsActionTypeWorkflows
}

// SetFake set fake values.
func (s *ActivationCreateInput) SetFake() {
	{
		{
			s.ServicePrincipalId = "string"
		}
	}
}

// SetFake set fake values.
func (s *ActivationOutput) SetFake() {
	{
		{
			s.ServicePrincipalId = "string"
		}
	}
	{
		{
			s.IsActive = true
		}
	}
	{
		{
			s.AutomatedActionLimit = int(0)
		}
	}
}

// SetFake set fake values.
func (s *ActivationUpdateInput) SetFake() {
	{
		{
			s.ServicePrincipalId = "string"
		}
	}
	{
		{
			s.IsActive = true
		}
	}
}

// SetFake set fake values.
func (s *AddonDatalakeNoPublicAccess) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AddonDatalakeNoPublicAccessEvaluationRuleId) SetFake() {
	*s = AddonDatalakeNoPublicAccessEvaluationRuleIdAddonDatalakeNoPublicAccess
}

// SetFake set fake values.
func (s *AddonDwhNoPublicAccess) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AddonDwhNoPublicAccessEvaluationRuleId) SetFake() {
	*s = AddonDwhNoPublicAccessEvaluationRuleIdAddonDwhNoPublicAccess
}

// SetFake set fake values.
func (s *AddonThreatDetectionEnabled) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AddonThreatDetectionEnabledEvaluationRuleId) SetFake() {
	*s = AddonThreatDetectionEnabledEvaluationRuleIdAddonThreatDetectionEnabled
}

// SetFake set fake values.
func (s *AddonThreatDetections) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AddonThreatDetectionsEvaluationRuleId) SetFake() {
	*s = AddonThreatDetectionsEvaluationRuleIdAddonThreatDetections
}

// SetFake set fake values.
func (s *AddonVulnerabilityDetections) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AddonVulnerabilityDetectionsEvaluationRuleId) SetFake() {
	*s = AddonVulnerabilityDetectionsEvaluationRuleIdAddonVulnerabilityDetections
}

// SetFake set fake values.
func (s *AutomatedActionID) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = AutomatedActionID(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionInput) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Action.SetFake()
		}
	}
	{
		{
			s.ExecutionCondition = "string"
		}
	}
	{
		{
			s.IsEnabled = true
		}
	}
}

// SetFake set fake values.
func (s *AutomatedActionOutput) SetFake() {
	{
		{
			s.AutomatedActionId.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Action.SetFake()
		}
	}
	{
		{
			s.ExecutionCondition = "string"
		}
	}
	{
		{
			s.IsEnabled = true
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *AutomatedActionsCreateApplicationJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsCreateApplicationJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsCreateApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsCreateApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsCreateApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsCreateApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsCreateApplicationProblemJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsCreateApplicationProblemJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsCreateApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsCreateApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsCreateApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsCreateApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsDeleteApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsDeleteApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsDeleteApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsDeleteApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsDeleteApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsDeleteApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsDeleteApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsDeleteApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsListApplicationJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsListApplicationJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsListApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsListApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsListApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsListApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsListApplicationProblemJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsListApplicationProblemJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsListApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsListApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsListApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsListApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsListOK) SetFake() {
	{
		{
			s.Items = nil
			for i := 0; i < 0; i++ {
				var elem AutomatedActionOutput
				{
					elem.SetFake()
				}
				s.Items = append(s.Items, elem)
			}
		}
	}
	{
		{
			s.NextPageToken.SetFake()
		}
	}
	{
		{
			s.PrevPageToken.SetFake()
		}
	}
	{
		{
			s.TotalSize = int(0)
		}
	}
}

// SetFake set fake values.
func (s *AutomatedActionsReadApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsReadApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsReadApplicationJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsReadApplicationJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsReadApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsReadApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsReadApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsReadApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsReadApplicationProblemJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsReadApplicationProblemJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsReadApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsReadApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsUpdateApplicationJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsUpdateApplicationJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsUpdateApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsUpdateApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsUpdateApplicationJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsUpdateApplicationJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsUpdateApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsUpdateApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsUpdateApplicationProblemJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsUpdateApplicationProblemJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsUpdateApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsUpdateApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsUpdateApplicationProblemJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsUpdateApplicationProblemJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *AutomatedActionsUpdateApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = AutomatedActionsUpdateApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *BadRequest) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Title.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Detail.SetFake()
		}
	}
	{
		{
			s.Instance.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BadRequestDetail) SetFake() {
	*s = BadRequestDetailInvalid
}

// SetFake set fake values.
func (s *BadRequestStatus) SetFake() {
	*s = BadRequestStatus400
}

// SetFake set fake values.
func (s *Conflict) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Title.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Detail.SetFake()
		}
	}
	{
		{
			s.Instance.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ConflictDetail) SetFake() {
	*s = ConflictDetailConflict
}

// SetFake set fake values.
func (s *ConflictStatus) SetFake() {
	*s = ConflictStatus409
}

// SetFake set fake values.
func (s *DbaEncryptionEnabled) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DbaEncryptionEnabledEvaluationRuleId) SetFake() {
	*s = DbaEncryptionEnabledEvaluationRuleIdDbaEncryptionEnabled
}

// SetFake set fake values.
func (s *DbaNoPublicIP) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DbaNoPublicIPEvaluationRuleId) SetFake() {
	*s = DbaNoPublicIPEvaluationRuleIdDbaNoPublicIP
}

// SetFake set fake values.
func (s *DiskEncryptionEnabled) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DiskEncryptionEnabledEvaluationRuleId) SetFake() {
	*s = DiskEncryptionEnabledEvaluationRuleIdDiskEncryptionEnabled
}

// SetFake set fake values.
func (s *ELBLoggingEnabled) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ELBLoggingEnabledEvaluationRuleId) SetFake() {
	*s = ELBLoggingEnabledEvaluationRuleIdElbLoggingEnabled
}

// SetFake set fake values.
func (s *EvaluationRule) SetFake() {
	{
		{
			s.Rule.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.IamRolesRequired = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.IamRolesRequired = append(s.IamRolesRequired, elem)
			}
		}
	}
	{
		{
			s.IsEnabled = true
		}
	}
}

// SetFake set fake values.
func (s *EvaluationRuleInput) SetFake() {
	{
		{
			s.Rule.SetFake()
		}
	}
	{
		{
			s.IsEnabled = true
		}
	}
}

// SetFake set fake values.
func (s *EvaluationRuleParametersEvaluationTarget) SetFake() {
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *EvaluationRuleParametersObjectStorageEvaluationTarget) SetFake() {
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.Sites = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Sites = append(s.Sites, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *EvaluationRuleParametersZonedEvaluationTarget) SetFake() {
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.Zones = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Zones = append(s.Zones, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *EvaluationRuleUnion) SetFake() {
	{
		{
			s.OneOf.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *EvaluationRuleUnionSum) SetFake() {
	var variant AddonDatalakeNoPublicAccess

	{
		variant.SetFake()
	}
	s.SetAddonDatalakeNoPublicAccess(variant)
}

// SetFake set fake values.
func (s *EvaluationRulesListApplicationJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesListApplicationJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesListApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesListApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesListApplicationJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesListApplicationJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesListApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesListApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesListApplicationProblemJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesListApplicationProblemJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesListApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesListApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesListApplicationProblemJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesListApplicationProblemJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesListApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesListApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesListOK) SetFake() {
	{
		{
			s.Items = nil
			for i := 0; i < 0; i++ {
				var elem EvaluationRule
				{
					elem.SetFake()
				}
				s.Items = append(s.Items, elem)
			}
		}
	}
	{
		{
			s.NextPageToken.SetFake()
		}
	}
	{
		{
			s.PrevPageToken.SetFake()
		}
	}
	{
		{
			s.TotalSize = int(0)
		}
	}
}

// SetFake set fake values.
func (s *EvaluationRulesReadApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesReadApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesReadApplicationJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesReadApplicationJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesReadApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesReadApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesReadApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesReadApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesReadApplicationProblemJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesReadApplicationProblemJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesReadApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesReadApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesUpdateApplicationJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesUpdateApplicationJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesUpdateApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesUpdateApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesUpdateApplicationJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesUpdateApplicationJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesUpdateApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesUpdateApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesUpdateApplicationProblemJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesUpdateApplicationProblemJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesUpdateApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesUpdateApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesUpdateApplicationProblemJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesUpdateApplicationProblemJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *EvaluationRulesUpdateApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = EvaluationRulesUpdateApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *Forbidden) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Title.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Detail.SetFake()
		}
	}
	{
		{
			s.Instance.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ForbiddenDetail) SetFake() {
	*s = ForbiddenDetailForbidden
}

// SetFake set fake values.
func (s *ForbiddenStatus) SetFake() {
	*s = ForbiddenStatus403
}

// SetFake set fake values.
func (s *IAMMemberOperationDetected) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *IAMMemberOperationDetectedEvaluationRuleId) SetFake() {
	*s = IAMMemberOperationDetectedEvaluationRuleIdIamMemberOperationDetected
}

// SetFake set fake values.
func (s *NoSQLEncryptionEnabled) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NoSQLEncryptionEnabledEvaluationRuleId) SetFake() {
	*s = NoSQLEncryptionEnabledEvaluationRuleIdNosqlEncryptionEnabled
}

// SetFake set fake values.
func (s *NotFound) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Title.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Detail.SetFake()
		}
	}
	{
		{
			s.Instance.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NotFoundDetail) SetFake() {
	*s = NotFoundDetailNotFound
}

// SetFake set fake values.
func (s *NotFoundStatus) SetFake() {
	*s = NotFoundStatus404
}

// SetFake set fake values.
func (s *ObjectStorageBucketACLChanged) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ObjectStorageBucketACLChangedEvaluationRuleId) SetFake() {
	*s = ObjectStorageBucketACLChangedEvaluationRuleIdObjectstorageBucketACLChanged
}

// SetFake set fake values.
func (s *ObjectStorageBucketEncryptionEnabled) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ObjectStorageBucketEncryptionEnabledEvaluationRuleId) SetFake() {
	*s = ObjectStorageBucketEncryptionEnabledEvaluationRuleIdObjectstorageBucketEncryptionEnabled
}

// SetFake set fake values.
func (s *OptBadRequestDetail) SetFake() {
	var elem BadRequestDetail
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBadRequestStatus) SetFake() {
	var elem BadRequestStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptConflictDetail) SetFake() {
	var elem ConflictDetail
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptConflictStatus) SetFake() {
	var elem ConflictStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptEvaluationRuleParametersEvaluationTarget) SetFake() {
	var elem EvaluationRuleParametersEvaluationTarget
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptEvaluationRuleParametersObjectStorageEvaluationTarget) SetFake() {
	var elem EvaluationRuleParametersObjectStorageEvaluationTarget
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptEvaluationRuleParametersZonedEvaluationTarget) SetFake() {
	var elem EvaluationRuleParametersZonedEvaluationTarget
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptForbiddenDetail) SetFake() {
	var elem ForbiddenDetail
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptForbiddenStatus) SetFake() {
	var elem ForbiddenStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNotFoundDetail) SetFake() {
	var elem NotFoundDetail
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNotFoundStatus) SetFake() {
	var elem NotFoundStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptTooManyRequestsDetail) SetFake() {
	var elem TooManyRequestsDetail
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptTooManyRequestsStatus) SetFake() {
	var elem TooManyRequestsStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUnauthorizedDetail) SetFake() {
	var elem UnauthorizedDetail
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUnauthorizedStatus) SetFake() {
	var elem UnauthorizedStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *ProjectActivationCreateApplicationJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationCreateApplicationJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationCreateApplicationJSONConflict) SetFake() {
	var unwrapped Conflict
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationCreateApplicationJSONConflict(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationCreateApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationCreateApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationCreateApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationCreateApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationCreateApplicationProblemJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationCreateApplicationProblemJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationCreateApplicationProblemJSONConflict) SetFake() {
	var unwrapped Conflict
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationCreateApplicationProblemJSONConflict(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationCreateApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationCreateApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationCreateApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationCreateApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationReadApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationReadApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationReadApplicationJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationReadApplicationJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationReadApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationReadApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationReadApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationReadApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationReadApplicationProblemJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationReadApplicationProblemJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationReadApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationReadApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationUpdateApplicationJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationUpdateApplicationJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationUpdateApplicationJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationUpdateApplicationJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationUpdateApplicationJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationUpdateApplicationJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationUpdateApplicationJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationUpdateApplicationJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationUpdateApplicationProblemJSONBadRequest) SetFake() {
	var unwrapped BadRequest
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationUpdateApplicationProblemJSONBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationUpdateApplicationProblemJSONForbidden) SetFake() {
	var unwrapped Forbidden
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationUpdateApplicationProblemJSONForbidden(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationUpdateApplicationProblemJSONNotFound) SetFake() {
	var unwrapped NotFound
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationUpdateApplicationProblemJSONNotFound(unwrapped)
}

// SetFake set fake values.
func (s *ProjectActivationUpdateApplicationProblemJSONUnauthorized) SetFake() {
	var unwrapped Unauthorized
	{
		unwrapped.SetFake()
	}
	*s = ProjectActivationUpdateApplicationProblemJSONUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *SakuraSimpleNotification) SetFake() {
	{
		{
			s.ServicePrincipalId = "string"
		}
	}
	{
		{
			s.NotificationGroupId = "string"
		}
	}
}

// SetFake set fake values.
func (s *SakuraWorkflows) SetFake() {
	{
		{
			s.ServicePrincipalId = "string"
		}
	}
	{
		{
			s.WorkflowId = "string"
		}
	}
	{
		{
			s.RevisionId.SetFake()
		}
	}
	{
		{
			s.RevisionAlias.SetFake()
		}
	}
	{
		{
			s.Args.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ServerNoPublicIP) SetFake() {
	{
		{
			s.EvaluationRuleId.SetFake()
		}
	}
	{
		{
			s.Parameter.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ServerNoPublicIPEvaluationRuleId) SetFake() {
	*s = ServerNoPublicIPEvaluationRuleIdServerNoPublicIP
}

// SetFake set fake values.
func (s *TooManyRequests) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Title.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Detail.SetFake()
		}
	}
	{
		{
			s.Instance.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *TooManyRequestsDetail) SetFake() {
	*s = TooManyRequestsDetailTooManyRequests
}

// SetFake set fake values.
func (s *TooManyRequestsStatus) SetFake() {
	*s = TooManyRequestsStatus429
}

// SetFake set fake values.
func (s *Unauthorized) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Title.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Detail.SetFake()
		}
	}
	{
		{
			s.Instance.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UnauthorizedDetail) SetFake() {
	*s = UnauthorizedDetailAuthenticationFailed
}

// SetFake set fake values.
func (s *UnauthorizedStatus) SetFake() {
	*s = UnauthorizedStatus401
}

// SetFake set fake values.
func (s *UnexpectedError) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Title.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Detail.SetFake()
		}
	}
	{
		{
			s.Instance.SetFake()
		}
	}
}
