// Code generated by ogen, DO NOT EDIT.

package v1

// AutomatedActionsDeleteParams is parameters of AutomatedActions_delete operation.
type AutomatedActionsDeleteParams struct {
	ActionId AutomatedActionID
}

// AutomatedActionsListParams is parameters of AutomatedActions_list operation.
type AutomatedActionsListParams struct {
	// 返却する要素の最大数。
	// サービス側でこの値より少なく返す場合がある。.
	PageSize OptInt `json:",omitempty,omitzero"`
	// このページトークンより後の要素を取得する。
	// このフィールドと `prev` は同時に指定できない。
	// ページネーション時、他のリクエストパラメータは元のリクエストと一致している必要がある。
	// 無効な場合は400 Bad Requestとなる。.
	Next OptString `json:",omitempty,omitzero"`
	// このページトークンより前の要素を取得する。
	// このフィールドと `next` は同時に指定できない。
	// ページネーション時、他のリクエストパラメータは元のリクエストと一致している必要がある。
	// 無効な場合は400 Bad Requestとなる。.
	Prev OptString `json:",omitempty,omitzero"`
}

// AutomatedActionsReadParams is parameters of AutomatedActions_read operation.
type AutomatedActionsReadParams struct {
	ActionId AutomatedActionID
}

// AutomatedActionsUpdateParams is parameters of AutomatedActions_update operation.
type AutomatedActionsUpdateParams struct {
	ActionId AutomatedActionID
}

// EvaluationRulesListParams is parameters of EvaluationRules_list operation.
type EvaluationRulesListParams struct {
	// 返却する要素の最大数。
	// サービス側でこの値より少なく返す場合がある。.
	PageSize OptInt `json:",omitempty,omitzero"`
	// このページトークンより後の要素を取得する。
	// このフィールドと `prev` は同時に指定できない。
	// ページネーション時、他のリクエストパラメータは元のリクエストと一致している必要がある。
	// 無効な場合は400 Bad Requestとなる。.
	Next OptString `json:",omitempty,omitzero"`
	// このページトークンより前の要素を取得する。
	// このフィールドと `next` は同時に指定できない。
	// ページネーション時、他のリクエストパラメータは元のリクエストと一致している必要がある。
	// 無効な場合は400 Bad Requestとなる。.
	Prev OptString `json:",omitempty,omitzero"`
}

// EvaluationRulesReadParams is parameters of EvaluationRules_read operation.
type EvaluationRulesReadParams struct {
	EvaluationRuleId EvaluationRuleID
}

// EvaluationRulesUpdateParams is parameters of EvaluationRules_update operation.
type EvaluationRulesUpdateParams struct {
	EvaluationRuleId EvaluationRuleID
}
