// Code generated by ogen, DO NOT EDIT.
package v1

type AutomatedActionsCreateRes interface {
	automatedActionsCreateRes()
}

type AutomatedActionsDeleteRes interface {
	automatedActionsDeleteRes()
}

type AutomatedActionsListRes interface {
	automatedActionsListRes()
}

type AutomatedActionsReadRes interface {
	automatedActionsReadRes()
}

type AutomatedActionsUpdateRes interface {
	automatedActionsUpdateRes()
}

type EvaluationRulesListRes interface {
	evaluationRulesListRes()
}

type EvaluationRulesReadRes interface {
	evaluationRulesReadRes()
}

type EvaluationRulesUpdateRes interface {
	evaluationRulesUpdateRes()
}

type ProjectActivationCreateRes interface {
	projectActivationCreateRes()
}

type ProjectActivationReadRes interface {
	projectActivationReadRes()
}

type ProjectActivationUpdateRes interface {
	projectActivationUpdateRes()
}
